FROM grafana/grafana-oss:latest

RUN grafana-cli plugins install grafana-piechart-panel
RUN grafana-cli plugins install yesoreyeram-infinity-datasource

COPY provisioning/ /etc/grafana/provisioning/

EXPOSE 3000

VOLUME /var/lib/grafana